alias lcdwrite="sudo python3 /home/pi/LCD1602/src/write.py"
echo "Successfully set alias lcdwrite"
alias lcdclear="sudo python3 /home/pi/LCD1602/src/clear.py"
echo "Successfully set alias lcdclear"
alias lcdhost="sudo python3 /home/pi/LCD1602/src/hostadress.py"
echo "Successfully set alias lcdhost"
